/*****************************************************************
* Filename     :  CmosSensor.H
* Author       :  yu.wei
* Company      :  ELAN
* VERSION      :  1.0
* CRYSTAL      :  8MHZ
* Creat date   :  2009/11/9
* tool ver.    :  WicePlus 2.7/eUIDE
* Description  :  modify for code conformity
*****************************************************************/
;-----------------------------------------------------------------
CmosSensorMM0200.H      EQU       CmosSensorMM0200.H




;-----------------------------------------------------------------
CmosSensorTypeSelect    EQU       0  ; select type,Default=0(MM0200DA)
                                     ; 0: MM0200DA (SPI Interface)
                                     ; 1: MM0200BA (I2C Interface)
                                     ; 2: MM0200FA   
                                     ; 3: MM0200CA         
                                     	
                                     	                                                                   