/*****************************************************************
* Filename     :  EM78M611rxP40M1v6V10 config
* Author       :  yu.wei
* Company      :  ELAN
* VERSION      :  1.0
* CRYSTAL	   :  8MHZ
* Creat date   :  2009/9/22
* tool ver.    :  WicePlus 2.7
* Description  :  modify for code conformity
*****************************************************************/
;-------------------------------------------------------------------------
config.h   EQU    config.h

;-------------------------------------------------------------------------


USED_PID_FUNCTION               EQU     0    
TotalGamePads                   EQU     6
DataBufferBase                  EQU     0x20  
ComuTime                        EQU     8     
RetryCNT                        EQU     0    
