;---------------------------------------------------
XX93C46_For_EM78M611.H         EQU        XX93C46_For_EM78M611.H
        READ        EQU     0X80    
        WRITE       EQU     0X40    
        ERASE       EQU     0XC0    
        EWEN        EQU     0X30   
        EWDS        EQU     0X00   
        ERAL        EQU     0X20    
        WRAL        EQU     0X10   
;--------------------------------------------------