/*****************************************************************
* Filename     :  filter file
* Author       :  yu.wei
* Company      :  ELAN
* Version      :  1.0
* Creat date   :  2009/11/10
* tool ver.    :  WicePlus 2.7/eUIDE
* Description  :  build for cmos sensor samping filter
*****************************************************************/
;-------------------------------------------------------------------
KalmanFilter.H          EQU    KalmanFilter.H


;-------------------------------------------------------------------
;kfComputeValue         EQU     0



